### ISSUE TITLE
JSON parsing error 

### ISSUE THREAD

**Issue by RanjithEy-Kore** [zserge/jsmn#129] opened 2018-03-13 13:17 UTC
I get a json parsing error in this case '{"value":"What is my \"Presence\"","condition":"equal"}'
this is failing double quotes are not handled properly.

**Comment by lgaitan** [comment] 2018-03-13 15:29
The double quotes inside the `value` property should be escaped. Otherwise your json will be indeed invalid.

```json
{
    "value": "What is my \"Presence\"",
    "condition":"equal"
}
```

**Comment by ahogen** [comment] 2018-05-14 16:02
Possibly a useful resource to avoid problems like this in the future: https://jsonlint.com

There are plugins for a variety of text editors to do JSON linting locally as well, but for quick checking, this website is nice.

**Closed as completed** 2018-07-17 05:18 UTC

**Comment by sparkplug23** [comment] 2021-01-27 00:07
I know this is old and what I ask is not pretty json formatting, but it is what I have to work with. 

I need a string, to contain `\"` after it is parsed i.e. `\\\"`.

A specific example I have is needing to parse an array of strings, which contain `\\\"`. Such as:

```cpp
{"commands":["something=\\\"value\\\"","this=\\\"that\\\""]}
```

From trying different escape values and looking in to the library, my understanding is this may not be possible, but I thought I would ask. My resultant output for this has been:

```cpp
something="value\"
this="that\"
```
and I have also gotten:

```cpp
something=\"valueue\"
this="thatat\"
```
I understand JSMN is strictly for basic json parsing, so what I am trying to parse is likely beyond the scope of the library, but thought I would ask in case I was being silly. 

Many thanks in advance.

**Comment by pt300** [comment] 2021-01-29 11:34
@sparkplug23 I don't really understand what you are trying to achieve. I can say that JSMN doesn't fully parse the JSON string. As in, if you have as an example a string with escape sequences, then those sequences won't be unescaped but left untouched in the token.

**Comment by sparkplug23** [comment] 2021-01-29 13:26
@pt300 As I said, I know its an ugly way of doing things, but its what I have. My exact use case is using openhab to send commands to a nextion panel, using an array of strings (each string is a command). Since setting text box elements also requires forwarding on unescaped characters, I need to basically include them twice as the json removes it the first time so the nextion panel can get the escaped value too. I have included an example below of a json command from openhab. 

Anyway, I got it to work by modifying JSMN. The problem appears to be two consecutive escaped characters inside a string not correctly being handled. For example, `\\\"` would correctly turn in to `\"`, but the string length would not shrink accordingly and the last 2 characters of the string remained (ie the null position was not shifted accordingly). My current thinking at this stage is because its a string in an array, its finding the second consecutive escaped character ( `\"`) as the end of the array element, and then moving on to the next token before finishing the string length etc. 

I only switched to using JSMN about a month ago from ArduinoJson. I am going to test what I have done further to see if it correctly helps or if I have managed to break something else, I will share my results when I am confident with how it behaves.

On your comment: `"As in, if you have as an example a string with escape sequences, then those sequences won't be unescaped but left untouched in the token."` 
If I am understanding you correctly, you are saying I should expect the string to remain "as is". Maybe its because I have them inside an array, but from my testing it fully tries to unescape everything. By debugging JSMN I can see any `\"` inside an array of strings is being treated as the end of a string, although its actually still part of it. This could be related to the consecutive escape characters I mentioned, I will test further. I just wanted to clarify that I might be seeing unexpected behaviour. 

Openhab mqtt message:
```cpp
{
  "commands": [
    "p[4].b[11].txt=\\\"12.3\\\"",
    "p[4].b[15].txt=\\\"22.3\\\"",
    "p[4].b[19].txt=\\\"32.3\\\"",
    "p[4].b[23].txt=\\\"67.0\\\""
  ]
}
```
Then using json array iterator passing each string as a command via serial to the display. 
Command 1 -> `p[4].b[11].txt=\"12.3\"` etc

**Comment by pt300** [comment] 2021-01-30 13:54
I can tell you that JSMN does not unescape anything. During parsing the escape sequences are understood but are left untouched. I believe that what you experience is either your printing function parsing the escape sequences or the method which you use to input the JSON string. In either case if you still believe the problem is with JSMN I suggest you open a new issue and provide code snippets.
